anime_mode=auto
fidelity=true
sd_mode=clean
sd_override=true
hd_override=true
shaders_enabled=true
sharpen_enabled=true
spatial_active=true
upmix_active=false
night_mode_active=false
custom_fsrcnnx_live_SD=~~/shaders/FSRCNNX_x2_16-0-4-1.glsl
custom_fsrcnnx_live_HD=~~/shaders/FSRCNNX_x2_16-0-4-1.glsl
custom_fsrcnnx_live_FHD=~~/shaders/FSRCNNX_x2_16-0-4-1.glsl
custom_fsrcnnx_anime_SD=~~/shaders/FSRCNNX_x2_16-0-4-1_enhance_anime.glsl
custom_fsrcnnx_anime_HD=~~/shaders/FSRCNNX_x2_8-0-4-1_LineArt.glsl
custom_fsrcnnx_anime_FHD=~~/shaders/FSRCNNX_x2_8-0-4-1_LineArt.glsl
custom_nnedi_live_SD=~~/shaders/nnedi3-nns256-win8x4.hook
custom_nnedi_live_HD=~~/shaders/nnedi3-nns64-win8x4.hook
up_next_enabled=true
skip_intro_enabled=true
