audio_output {
    type            "pipewire"
    name            "PipeWire Sound Server"
}

audio_output {
    type            "fifo"
    name            "my_fifo"
    path            "/tmp/mpd.fifo"
    format          "44100:16:2"
}

# Listen on localhost TCP for your plugin
bind_to_address "/run/user/1000/mpd/socket"
port "6600"

# Log to systemd
log_file "syslog"

# Auto update
auto_update "yes"
auto_update_depth "10"

# Music database
music_directory    "/mnt/HDD_STORAGE/Music"
playlist_directory "/home/gomi/.config/mpd/playlists"
db_file            "/home/gomi/.config/mpd/database"
state_file         "/home/gomi/.config/mpd/state"
sticker_file       "/home/gomi/.config/mpd/sticker.sql"
